models:
  - name: stg_health_spending
    columns:
      - name: category
        tests: [not_null]
      - name: total_spending
        tests: [not_null]
      - name: population_k
        tests: [not_null]
      - name: spending_per_capita
        tests: [not_null]
