version: 2

models:
  - name: mart_health_spending
    description: "Aggregated health spending metrics for Tableau dashboards"
    tests:
      - not_empty
    columns:
      - name: province
      - name: year
      - name: category
      - name: total_spending
      - name: avg_spending_per_capita
      - name: avg_yoy_pct_change
