version: 2

models:
  - name: mart_health_spending
    description: "Aggregated health spending metrics for Tableau dashboards"
    columns:
      - name: province
        tests: [not_null]
      - name: year
        tests: [not_null]
      - name: category
        tests: [not_null]
      - name: total_spending
        tests: [not_null]
      - name: avg_spending_per_capita
        tests: [not_null]
      - name: avg_prev_spending_pc
